Repository nextcloud/sharepoint, pull requests merged in 2022-04, with the labels that each got.

#62 Bump phpSPO to 2.4, brings 2019 support
  README.md
  composer.json
  composer.lock
  lib/Client.php
  lib/ClientFactory.php
  lib/Command/ListLibraries.php
  lib/ContextsFactory.php
  lib/Helper/RequestsWrapper.php
  lib/Storage/Storage.php
  tests/Unit/ClientTest.php
  tests/Unit/StorageTest.php
Labels: 3. to review, backport-request, enhancement

#122 Update master php testing versions
  .github/workflows/lint.yml
  .github/workflows/phpunit-mysql.yml
  .github/workflows/phpunit-oci.yml
  .github/workflows/phpunit-pgsql.yml
  .github/workflows/phpunit-sqlite.yml
  .github/workflows/phpunit.yml
  composer.json
  composer.lock
  phpunit.integration.xml
  tests/Unit/ClientTest.php
Labels: 3. to review

#118 [stable20] Bump phpSPO to 2.4, brings 2019 support
  README.md
  composer.json
  composer.lock
  lib/Client.php
  lib/ClientFactory.php
  lib/Command/ListLibraries.php
  lib/ContextsFactory.php
  lib/Helper/RequestsWrapper.php
  lib/Storage/Storage.php
  tests/Unit/ClientTest.php
  tests/Unit/StorageTest.php
Labels: 3. to review

#127 add appstore workflow
  .github/workflows/appstore-build-publish.yml
Labels: 3. to review, backport-request

#132 1.8.2
  appinfo/info.xml
Labels: 4. to release

#133 1.9.1
  appinfo/info.xml
Labels: 4. to release

#134 1.10.1
  appinfo/info.xml
Labels: 4. to release

#136 Update version on master
  appinfo/info.xml
Labels: 4. to release

#137 Updating command-rebase.yml workflow from template
  .github/workflows/command-rebase.yml
Labels: dependencies
