Repository nextcloud/sharepoint, pull requests merged in 2023-03, with the labels that each got.

#171 chore: Add Nextcloud 27 support on master
  .github/workflows/phpunit-mysql.yml
  appinfo/info.xml
Labels: 4. to release

#170 chore(CI): Adjust testing matrix for Nextcloud 26 on stable26
  .github/workflows/integration.yml
  .github/workflows/phpunit-mysql.yml
  .github/workflows/phpunit-oci.yml
  .github/workflows/phpunit-pgsql.yml
  .github/workflows/phpunit-sqlite.yml
Labels: 4. to release

#169 SP files are case insensitive. Lowercasing the url may save requests.
  lib/Storage/Storage.php
  tests/Unit/StorageTest.php
Labels: 3. to review, backport-request, enhancement

#175 v1.12.1
  appinfo/info.xml
Labels: 3. to review

#176 build step updates
  composer.json
  composer/autoload.php
  krankerl.toml
  lib/AppInfo/Application.php
Labels: 3. to review, backport-request
