Repository nextcloud/sharepoint, pull requests merged in 2023-02, with the labels that each got.

#158 fix stream upload headers
  lib/Client.php
Labels: 4. to release, backport-request, bug

#159 [stable25] fix stream upload headers
  lib/Client.php
Labels: 3. to review, bug

#160 [stable24] fix stream upload headers
  lib/Client.php
Labels: 3. to review, bug

#154 improve PHP 8.x compatibility and special char fixes
  composer.json
  composer.lock
  lib/Client.php
  lib/ClientFactory.php
  lib/Storage/Storage.php
  tests/Unit/ClientTest.php
  tests/Unit/StorageTest.php
Labels: 3. to review, backport-request, bug

#163 exclude .php-cs-fixer.dist.php from packaging
  .nextcloudignore
Labels: 4. to release

#161 [stable25] improve PHP 8.x compatibility and special char fixes
  composer.json
  composer.lock
  lib/Client.php
  lib/ClientFactory.php
  lib/Storage/Storage.php
  tests/Unit/ClientTest.php
  tests/Unit/StorageTest.php
Labels: 3. to review, bug

#162 [stable24] improve PHP 8.x compatibility and special char fixes
  composer.json
  composer.lock
  lib/Client.php
  lib/ClientFactory.php
  lib/Storage/Storage.php
  tests/Unit/ClientTest.php
  tests/Unit/StorageTest.php
Labels: 3. to review, bug

#164 [stable25] exclude .php-cs-fixer.dist.php from packaging
  .nextcloudignore
Labels: 3. to review

#165 [stable24] exclude .php-cs-fixer.dist.php from packaging
  .nextcloudignore
Labels: 3. to review

#166 fix handling of sharepoint error codes
  lib/Client.php
  tests/Unit/ClientTest.php
Labels: 4. to release, backport-request, bug
